from googleapiclient.discovery import build
import os
from dotenv import load_dotenv


load_dotenv()

API_KEY = os.getenv("YOUTUBE_API_KEY")

youtube = build(
    "youtube",
    "v3",
    developerKey=API_KEY
)


def search_channels(query, max_results=50):
    """
    Search YouTube for channels related to a search query.
    """

    response = youtube.search().list(
        part="snippet",
        q=query,
        type="channel",
        maxResults=max_results
    ).execute()

    channels = []

    for item in response.get("items", []):

        channel_id = item["snippet"]["channelId"]

        channels.append({
            "channel_id": channel_id,
            "name": item["snippet"]["title"],
            "description": item["snippet"]["description"],
            "profile_url": (
                f"https://www.youtube.com/channel/"
                f"{channel_id}"
            )
        })

    return channels


def get_channel_details(channel_ids):
    """
    Get subscriber count and channel information
    for the discovered channels.
    """

    details = []

    # YouTube allows up to 50 channel IDs per request
    for i in range(0, len(channel_ids), 50):

        batch = channel_ids[i:i + 50]

        response = youtube.channels().list(
            part="snippet,statistics",
            id=",".join(batch)
        ).execute()

        for channel in response.get("items", []):

            statistics = channel.get(
                "statistics",
                {}
            )

            snippet = channel.get(
                "snippet",
                {}
            )

            subscribers = int(
                statistics.get(
                    "subscriberCount",
                    0
                )
            )

            details.append({
                "channel_id": channel["id"],
                "name": snippet.get(
                    "title",
                    ""
                ),
                "description": snippet.get(
                    "description",
                    ""
                ),
                "profile_url": (
                    f"https://www.youtube.com/channel/"
                    f'{channel["id"]}'
                ),
                "followers": subscribers
            })

    return details


def discover_influencers(
    niche,
    search_queries,
    min_followers=5000,
    max_followers=100000
):
    """
    Discover YouTube micro-influencer candidates.

    Parameters:
        niche: User-selected niche.
        search_queries: Keywords/topics generated by the LLM.
        min_followers: Minimum follower/subscriber count.
        max_followers: Maximum follower/subscriber count.

    Returns:
        List of eligible influencer candidates.
    """

    all_channels = []

    # --------------------------------
    # Search YouTube
    # --------------------------------

    for query in search_queries:

        print(
            f"Searching: {query}"
        )

        channels = search_channels(
            query,
            max_results=50
        )

        all_channels.extend(
            channels
        )

    # --------------------------------
    # Remove duplicate channels
    # --------------------------------

    unique_channels = {}

    for channel in all_channels:

        channel_id = channel[
            "channel_id"
        ]

        unique_channels[
            channel_id
        ] = channel

    print(
        f"\nUnique channels found: "
        f"{len(unique_channels)}"
    )

    # --------------------------------
    # Get channel details
    # --------------------------------

    channel_ids = list(
        unique_channels.keys()
    )

    channels = get_channel_details(
        channel_ids
    )

    # --------------------------------
    # Apply basic micro-influencer filter
    # --------------------------------

    influencers = []

    for channel in channels:

        followers = channel[
            "followers"
        ]

        if (
            min_followers
            <= followers
            <= max_followers
        ):

            channel["platform"] = "YouTube"

            channel["niche"] = niche

            channel["status"] = "Candidate"

            influencers.append(
                channel
            )

    print(
        f"Eligible micro-influencers: "
        f"{len(influencers)}"
    )

    return influencers